# Generated by Django 5.0.14 on 2026-05-23 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('estructura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones', to=settings.AUTH_USER_MODEL)),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones', to='estructura.subarea')),
            ],
            options={
                'verbose_name': 'Planificacion',
                'verbose_name_plural': 'Planificaciones',
                'db_table': 'planificacion',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones_detalle', to='actividades.actividad')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='planificacion.planificacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de Planificacion',
                'verbose_name_plural': 'Detalles de Planificacion',
                'db_table': 'planificacion_detalle',
            },
        ),
    ]
