# Generated by Django 5.0.14 on 2026-05-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificaciondetalle',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
