# Generated by Django 5.0.14 on 2026-05-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_alter_planificaciondetalle_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='cerrada',
            field=models.BooleanField(default=False, help_text='Al cerrar una planificacion no se pueden agregar mas actividades'),
        ),
    ]
