# Generated by Django 5.0.14 on 2026-05-23 15:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_tipoactividad_requiere_fecha_limite'),
        ('planificacion', '0003_planificacion_cerrada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planificaciondetalle',
            unique_together={('planificacion', 'actividad', 'user')},
        ),
    ]
