# Generated by Django 5.0.14 on 2026-05-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_alter_planificaciondetalle_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificaciondetalle',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha limite o deadline de la actividad', null=True),
        ),
        migrations.AlterField(
            model_name='planificaciondetalle',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, help_text='Fecha en que aparece en el tablero del usuario', null=True),
        ),
    ]
