# Generated by Django 5.0.14 on 2026-05-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0005_planificaciondetalle_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planificaciondetalle',
            old_name='fecha_limite',
            new_name='fecha_programada',
        ),
    ]
