# Generated by Django 5.0.14 on 2026-06-06 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0006_rename_fecha_limite_planificaciondetalle_fecha_programada'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Vincula esta planificacion a un proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones', to='proyectos.proyecto'),
        ),
    ]
