# Generated by Django 5.0.14 on 2026-06-01 01:26

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_empresa_codigo_alter_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.foto_upload_path),
        ),
    ]
