# Generated by Django 5.0.14 on 2026-06-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles_adicionales',
            field=models.ManyToManyField(blank=True, related_name='usuarios_extra', to='accounts.rol'),
        ),
    ]
