# Generated by Django 5.0.14 on 2026-06-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_roles_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maneja_proyectos',
            field=models.BooleanField(default=False, verbose_name='Maneja proyectos'),
        ),
    ]
