# Generated by Django 5.0.14 on 2026-05-23 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subareas', to='estructura.area')),
            ],
            options={
                'verbose_name': 'SubArea',
                'verbose_name_plural': 'SubAreas',
                'db_table': 'subarea',
            },
        ),
        migrations.CreateModel(
            name='UserSubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='estructura.subarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subareas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-SubArea',
                'verbose_name_plural': 'Usuarios-SubAreas',
                'db_table': 'user_subarea',
                'unique_together': {('user', 'subarea')},
            },
        ),
    ]
