# Generated by Django 5.0.14 on 2026-05-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subarea',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
