# Generated by Django 5.0.14 on 2026-05-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0002_area_codigo_subarea_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
