# Generated by Django 5.0.14 on 2026-05-28 22:54

import django.db.models.deletion
from django.db import migrations, models


def migrar_empresa_area(apps, schema_editor):
    Area = apps.get_model("estructura", "Area")
    EmpresaArea = apps.get_model("estructura", "EmpresaArea")
    for area in Area.objects.all():
        empresa_id = getattr(area, "empresa_id", None)
        if empresa_id:
            EmpresaArea.objects.get_or_create(area=area, empresa_id=empresa_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_empresa_codigo_alter_user_rol"),
        ("estructura", "0004_alter_area_codigo_alter_subarea_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresaArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_update", models.DateTimeField(auto_now=True)),
                ("area", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="relaciones_empresas", to="estructura.area")),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="areas_funcionales", to="accounts.empresa")),
            ],
            options={
                "verbose_name": "Empresa-Area",
                "verbose_name_plural": "Empresas-Areas",
                "db_table": "empresa_area",
                "unique_together": {("empresa", "area")},
            },
        ),
        migrations.RunPython(migrar_empresa_area, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="area",
            name="empresa",
        ),
        migrations.AlterField(
            model_name="area",
            name="nombre",
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="subarea",
            unique_together={("area", "nombre")},
        ),
        migrations.AddField(
            model_name="area",
            name="empresas",
            field=models.ManyToManyField(related_name="areas_m2m", through="estructura.EmpresaArea", to="accounts.empresa"),
        ),
        migrations.CreateModel(
            name="EmpresaSubArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activo", models.BooleanField(default=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subareas_funcionales", to="accounts.empresa")),
                ("subarea", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="empresas_permitidas", to="estructura.subarea")),
            ],
            options={
                "verbose_name": "Empresa-SubArea",
                "verbose_name_plural": "Empresas-SubAreas",
                "db_table": "empresa_subarea",
                "unique_together": {("empresa", "subarea")},
            },
        ),
    ]
