# Generated by Django 5.0.14 on 2026-06-06 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0010_remove_actividad_es_flash'),
        ('estructura', '0005_remove_area_empresa_alter_area_nombre_and_more'),
        ('gestion', '0017_alter_tiempoinactividad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'etiqueta',
            },
        ),
        migrations.CreateModel(
            name='HistoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('criterios_aceptacion', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('must', 'Must Have'), ('should', 'Should Have'), ('could', 'Could Have'), ('wont', "Won't Have")], default='should', max_length=10)),
                ('puntos_historia', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('backlog', 'Backlog'), ('sprint_backlog', 'Sprint Backlog'), ('en_progreso', 'En Progreso'), ('revision', 'En Revision'), ('done', 'Done')], default='backlog', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_creadas', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, to='proyectos.etiqueta')),
            ],
            options={
                'db_table': 'historia_usuario',
                'ordering': ['proyecto', 'orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('pasos_reproducir', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('bug', 'Bug'), ('mejora', 'Mejora'), ('pregunta', 'Pregunta / Soporte'), ('riesgo', 'Riesgo')], default='bug', max_length=20)),
                ('severidad', models.CharField(choices=[('critica', 'Critica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('triaged', 'En Triage'), ('en_progreso', 'En Progreso'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada'), ('duplicada', 'Duplicada')], default='abierta', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencia', to='gestion.asignacionactividad')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, to='proyectos.etiqueta')),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='proyectos.historiausuario')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidencia',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_incidencias', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='proyectos.incidencia')),
            ],
            options={
                'db_table': 'comentario_incidencia',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('objetivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='estructura.area')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_gestionados', to=settings.AUTH_USER_MODEL)),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='estructura.subarea')),
            ],
            options={
                'db_table': 'proyecto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='incidencia',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='proyectos.proyecto'),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('objetivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('activo', 'Activo'), ('finalizado', 'Finalizado')], default='planificado', max_length=20)),
                ('numero', models.IntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'sprint',
                'ordering': ['proyecto', 'numero'],
                'unique_together': {('proyecto', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias', to='proyectos.sprint'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('bug', 'Bug'), ('mejora', 'Mejora'), ('documentacion', 'Documentacion'), ('prueba', 'Prueba'), ('diseno', 'Diseno')], default='tarea', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('revision', 'En Revision'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('estimacion_horas', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('actividad_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_proyecto', to='actividades.actividad')),
                ('asignacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea_proyecto', to='gestion.asignacionactividad')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('bloqueada_por', models.ManyToManyField(blank=True, related_name='bloquea_a', to='proyectos.tarea')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, to='proyectos.etiqueta')),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.historiausuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.proyecto')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='proyectos.sprint')),
            ],
            options={
                'db_table': 'tarea',
                'ordering': ['proyecto', 'sprint', 'historia__orden', 'fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='proyectos.tarea'),
        ),
        migrations.CreateModel(
            name='MiembroProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('manager', 'Project Manager'), ('product_owner', 'Product Owner'), ('scrum_master', 'Scrum Master'), ('developer', 'Developer'), ('tester', 'QA / Tester'), ('viewer', 'Observador')], default='developer', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_miembro', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'miembro_proyecto',
                'unique_together': {('proyecto', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='etiqueta',
            unique_together={('proyecto', 'nombre')},
        ),
    ]
