# Generated by Django 5.0.14 on 2026-06-06 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembroproyecto',
            name='rol',
            field=models.CharField(choices=[('lider', 'Lider de Proyecto'), ('responsable', 'Responsable'), ('revisor', 'Revisor / QA'), ('aprobador', 'Aprobador'), ('ejecutor', 'Ejecutor'), ('observador', 'Observador')], default='developer', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('historia_completada', 'Historia completada'), ('sprint_iniciado', 'Sprint iniciado'), ('sprint_finalizado', 'Sprint finalizado'), ('incidencia_resuelta', 'Incidencia resuelta'), ('tarea_finalizada', 'Tarea finalizada'), ('comentario', 'Comentario'), ('bloqueo', 'Bloqueo reportado')], max_length=30)),
                ('descripcion', models.TextField()),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='proyectos.proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_avance',
                'ordering': ['-fecha'],
            },
        ),
    ]
