# Generated by Django 5.0.14 on 2026-06-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0005_remove_area_empresa_alter_area_nombre_and_more'),
        ('proyectos', '0002_alter_miembroproyecto_rol_registroavance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='estructura.area'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='estructura.subarea'),
        ),
    ]
