# Generated by Django 5.0.14 on 2026-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0005_remove_area_empresa_alter_area_nombre_and_more'),
        ('proyectos', '0003_alter_proyecto_area_alter_proyecto_subarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='area',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='subarea',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='subareas',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='estructura.subarea'),
        ),
    ]
