# Generated by Django 5.0.14 on 2026-06-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_remove_proyecto_area_remove_proyecto_subarea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(choices=[('historia', 'Historia de Usuario'), ('tarea', 'Tarea'), ('incidencia', 'Incidencia')], max_length=20)),
                ('estado_origen', models.CharField(max_length=30)),
                ('estado_destino', models.CharField(max_length=30)),
                ('requiere_rol', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'workflow_config',
                'unique_together': {('proyecto', 'entidad', 'estado_origen', 'estado_destino')},
            },
        ),
    ]
