# Generated by Django 5.0.14 on 2026-06-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_workflowconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha limite'),
        ),
    ]
