# Generated by Django 5.0.14 on 2026-06-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_tarea_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('must', 'Must Have'), ('should', 'Should Have'), ('could', 'Could Have'), ('wont', "Won't Have")], default='should', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('pausada', 'Pausada'), ('bloqueada', 'Bloqueada'), ('finalizada', 'Finalizada'), ('revision', 'En Revision'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
