# Generated by Django 5.0.14 on 2026-06-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_maneja_proyectos'),
        ('proyectos', '0007_tarea_prioridad_alter_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='accounts.empresa'),
        ),
    ]
