# Generated by Django 5.0.14 on 2026-06-19 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_proyecto_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='estado',
            field=models.CharField(choices=[('planificado', 'Planificado'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20),
        ),
        migrations.CreateModel(
            name='ComentarioHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='proyectos.historiausuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_historia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comentario_historia',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
