# Generated by Django 5.0.14 on 2026-06-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_comentario_historia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='adjunto',
            field=models.FileField(blank=True, help_text='Archivo adjunto opcional', null=True, upload_to='incidencias/'),
        ),
        migrations.AlterField(
            model_name='miembroproyecto',
            name='rol',
            field=models.CharField(choices=[('lider', 'Lider de Proyecto'), ('responsable', 'Responsable'), ('revisor', 'Revisor / QA'), ('aprobador', 'Aprobador'), ('ejecutor', 'Ejecutor'), ('observador', 'Observador')], default='ejecutor', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroavance',
            name='tipo',
            field=models.CharField(choices=[('historia_completada', 'Historia completada'), ('historia_aprobada', 'Historia aprobada'), ('historia_rechazada', 'Historia rechazada'), ('historia_creada', 'Historia creada'), ('historia_editada', 'Historia editada'), ('sprint_iniciado', 'Sprint iniciado'), ('sprint_finalizado', 'Sprint finalizado'), ('sprint_creado', 'Sprint creado'), ('incidencia_resuelta', 'Incidencia resuelta'), ('incidencia_creada', 'Incidencia creada'), ('tarea_finalizada', 'Tarea finalizada'), ('tarea_creada', 'Tarea creada'), ('tarea_rechazada', 'Tarea rechazada'), ('comentario', 'Comentario'), ('bloqueo', 'Bloqueo reportado'), ('proyecto_creado', 'Proyecto creado'), ('proyecto_editado', 'Proyecto editado'), ('proyecto_cancelado', 'Proyecto cancelado'), ('proyecto_pausado', 'Proyecto pausado'), ('proyecto_reanudado', 'Proyecto reanudado'), ('miembro_agregado', 'Miembro agregado'), ('miembro_removido', 'Miembro removido')], max_length=30),
        ),
    ]
