# Generated by Django 5.0.14 on 2026-06-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_historia_aprobador_tarea_revisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='workflow_bloqueado',
            field=models.BooleanField(default=False, help_text='Si True, no se puede cambiar la plantilla de flujo'),
        ),
    ]
