# Generated by Django 5.0.14 on 2026-06-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_proyecto_workflow_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
