# Generated by Django 5.0.14 on 2026-06-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_fecha_update_y_historia_setnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='proyectos.historiausuario'),
        ),
    ]
