# Generated by Django 5.0.14 on 2026-07-02 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_historia_setnull'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasos', models.JSONField(default=list, help_text='\n        Lista de pasos de revision. Cada paso: {"orden":1,"etiqueta":"...","rol":"revisor","user_ids":[6],"tipo":"revision"}\n        user_ids vacio = tomar todos los miembros con ese rol (paralelo).\n    ')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flujo_personalizado', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'flujo_personalizado',
            },
        ),
    ]
