# Generated by Django 5.0.14 on 2026-05-23 03:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('planificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('EnCurso', 'En Curso'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada'), ('Trasladada', 'Trasladada')], default='Pendiente', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='actividades.actividad')),
                ('planificacion_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='planificacion.planificaciondetalle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignacion de Actividad',
                'verbose_name_plural': 'Asignaciones de Actividad',
                'db_table': 'asignacion_actividad',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='gestion.asignacionactividad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('Inicio', 'Inicio'), ('Pausa', 'Pausa'), ('Reanudacion', 'Reanudacion'), ('Finalizacion', 'Finalizacion'), ('Traslado', 'Traslado')], max_length=20)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('nro_actividad', models.CharField(blank=True, help_text='Nro secuencial manual de actividades realizadas', max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='gestion.asignacionactividad')),
            ],
            options={
                'verbose_name': 'Registro de Tiempo',
                'verbose_name_plural': 'Registros de Tiempo',
                'db_table': 'registro_tiempo',
            },
        ),
        migrations.CreateModel(
            name='TrasladoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('asignacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_destino', to='gestion.asignacionactividad')),
                ('asignacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='gestion.asignacionactividad')),
                ('user_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_recibidos', to=settings.AUTH_USER_MODEL)),
                ('user_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_hechos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traslado de Actividad',
                'verbose_name_plural': 'Traslados de Actividad',
                'db_table': 'traslado_actividad',
            },
        ),
        migrations.CreateModel(
            name='Colaboracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboraciones', to='gestion.asignacionactividad')),
                ('user_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboraciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaboracion',
                'verbose_name_plural': 'Colaboraciones',
                'db_table': 'colaboracion',
                'unique_together': {('asignacion', 'user_colaborador')},
            },
        ),
    ]
