# Generated by Django 5.0.14 on 2026-05-23 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_tipoactividad_requiere_fecha_limite'),
        ('gestion', '0001_initial'),
        ('planificacion', '0004_alter_planificaciondetalle_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignacionactividad',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('estado', 'EnCurso')), fields=('user',), name='unique_en_curso_por_usuario'),
        ),
    ]
