# Generated by Django 5.0.14 on 2026-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_asignacionactividad_unique_en_curso_por_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotiempo',
            name='motivo_pausa',
            field=models.CharField(blank=True, choices=[('', 'Sin motivo'), ('Almuerzo', 'Almuerzo'), ('Reunion', 'Reunion'), ('Descanso', 'Descanso'), ('Interrupcion', 'Interrupcion'), ('Cambio de prioridad', 'Cambio de prioridad'), ('Actividad no programada', 'Actividad no programada'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
    ]
