# Generated by Django 5.0.14 on 2026-05-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_tipoactividad_requiere_fecha_limite'),
        ('gestion', '0003_registrotiempo_motivo_pausa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trasladoactividad',
            name='asignacion_destino',
        ),
        migrations.AddField(
            model_name='trasladoactividad',
            name='actividad_reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_reemplazo', to='actividades.actividad'),
        ),
        migrations.AddField(
            model_name='trasladoactividad',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Cancelado', 'Cancelado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrotiempo',
            name='motivo_pausa',
            field=models.CharField(blank=True, choices=[('', 'Sin motivo'), ('Almuerzo', 'Almuerzo / Descanso'), ('Interrupcion', 'Interrupcion'), ('Cambio de prioridad', 'Cambio de prioridad / Actividad programada'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
    ]
