# Generated by Django 5.0.14 on 2026-05-23 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_trasladoactividad_asignacion_destino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactividad',
            name='origen',
            field=models.CharField(blank=True, help_text='Planificacion, Traslado, Manual', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='origen_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_origen', to=settings.AUTH_USER_MODEL),
        ),
    ]
