# Generated by Django 5.0.14 on 2026-05-23 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_tipoactividad_requiere_fecha_limite'),
        ('gestion', '0005_asignacionactividad_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladoactividad',
            name='asignacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_destino', to='gestion.asignacionactividad'),
        ),
        migrations.AddConstraint(
            model_name='trasladoactividad',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('estado', 'Pendiente')), fields=('asignacion_origen', 'user_destino'), name='unique_traslado_pendiente'),
        ),
    ]
