# Generated by Django 5.0.14 on 2026-05-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_trasladoactividad_asignacion_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactividad',
            name='tiempo_total_segundos',
            field=models.IntegerField(default=0, help_text='Tiempo cacheado hasta la ultima pausa/finalizacion'),
        ),
    ]
