# Generated by Django 5.0.14 on 2026-05-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_asignacionactividad_tiempo_total_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactividad',
            name='tiempo_pausado_segundos',
            field=models.IntegerField(default=0, help_text='Tiempo total en pausa cacheado'),
        ),
    ]
