# Generated by Django 5.0.14 on 2026-05-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_asignacionactividad_tiempo_pausado_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactividad',
            name='prorroga_count',
            field=models.IntegerField(default=0, help_text='Cantidad de veces que fue reprogramado'),
        ),
    ]
