# Generated by Django 5.0.14 on 2026-05-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_asignacionactividad_prorroga_count'),
        ('planificacion', '0006_rename_fecha_limite_planificaciondetalle_fecha_programada'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='planificacion.planificaciondetalle'),
        ),
    ]
