# Generated by Django 5.0.14 on 2026-05-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_comentario_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactividad',
            name='dias_vencida',
            field=models.IntegerField(default=0, help_text='Dias de retraso al momento de finalizar/trasladar'),
        ),
    ]
