# Generated by Django 5.0.14 on 2026-05-29 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_asignacionactividad_dias_vencida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoMuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('motivo', models.CharField(default='Tiempo sin actividad', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiempos_muertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tiempo Muerto',
                'verbose_name_plural': 'Tiempos Muertos',
                'db_table': 'tiempo_muerto',
                'ordering': ['-fecha', '-inicio'],
            },
        ),
    ]
