# Generated by Django 5.0.14 on 2026-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_tiempomuerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactividad',
            name='entregable',
            field=models.FileField(blank=True, null=True, upload_to='entregables/'),
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='estado_revision',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='revision_comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionactividad',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('EnCurso', 'En Curso'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada'), ('Trasladada', 'Trasladada'), ('Revision', 'En Revision')], default='Pendiente', max_length=20),
        ),
    ]
