# Generated by Django 5.0.14 on 2026-06-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_asignacionactividad_entregable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactividad',
            name='nombre_actividad',
            field=models.CharField(blank=True, help_text='Nombre congelado de la actividad al momento de la asignacion', max_length=300),
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='nombre_tipo',
            field=models.CharField(blank=True, help_text='Nombre congelado del tipo de actividad al momento de la asignacion', max_length=200),
        ),
    ]
