# Generated by Django 5.0.14 on 2026-06-02 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_asignacionactividad_nombre_actividad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_revision', to='gestion.asignacionactividad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_hechas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Revision',
                'verbose_name_plural': 'Historial de Revisiones',
                'db_table': 'revision_historial',
                'ordering': ['-fecha'],
            },
        ),
    ]
