# Generated by Django 5.0.14 on 2026-06-02 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_revisionhistorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiempoMuerto',
            new_name='TiempoInactividad',
        ),
        migrations.AlterModelTable(
            name='TiempoInactividad',
            table='tiempo_inactividad',
        ),
    ]
