# Generated by Django 5.0.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_rename_tiempomuerto_to_tiempoinactividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiempoinactividad',
            options={'ordering': ['-fecha', '-inicio'], 'verbose_name': 'Tiempo de Inactividad', 'verbose_name_plural': 'Tiempos de Inactividad'},
        ),
        migrations.AlterField(
            model_name='tiempoinactividad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiempos_inactividad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tiempoinactividad',
            constraint=models.CheckConstraint(check=models.Q(('fin__isnull', True), ('fin__gt', models.F('inicio')), _connector='OR'), name='fin_posterior_a_inicio'),
        ),
    ]
