# Generated by Django 5.0.14 on 2026-06-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_tiempoinactividad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactividad',
            name='revision_entregable',
            field=models.FileField(blank=True, help_text='Archivo entregable del revisor', null=True, upload_to='entregables_revision/'),
        ),
        migrations.AlterField(
            model_name='asignacionactividad',
            name='entregable',
            field=models.FileField(blank=True, help_text='Archivo entregable del ejecutor', null=True, upload_to='entregables/'),
        ),
    ]
