# Generated by Django 5.0.14 on 2026-05-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='tiempo_estimado',
        ),
    ]
