# Generated by Django 5.0.14 on 2026-05-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_remove_actividad_tiempo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='requiere_fecha_limite',
            field=models.BooleanField(default=True, help_text='Si esta activo, al planificar esta actividad la fecha limite sera obligatoria'),
        ),
    ]
