# Generated by Django 5.0.14 on 2026-05-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_tipoactividad_requiere_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
