# Generated by Django 5.0.14 on 2026-05-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actividad_codigo_tipoactividad_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
