# Generated by Django 5.0.14 on 2026-05-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_alter_tipoactividad_codigo_alter_actividad_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='es_flash',
            field=models.BooleanField(default=False, help_text='Si esta activo, la actividad aparece como opcion de evento flash'),
        ),
    ]
