# Generated by Django 5.0.14 on 2026-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_actividad_es_flash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='requiere_entregable',
            field=models.BooleanField(default=False, help_text='Si esta activo, la actividad requiere archivo entregable al finalizar'),
        ),
    ]
