# Generated by Django 5.0.14 on 2026-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_tipoactividad_requiere_entregable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='es_flash',
            field=models.BooleanField(default=False, help_text='Si esta activo, las actividades de este tipo aparecen como evento flash'),
        ),
    ]
