# Generated by Django 5.0.14 on 2026-06-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_tipoactividad_es_flash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='es_flash',
        ),
    ]
