# Generated by Django 5.0.14 on 2026-06-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_remove_actividad_es_flash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='solo_proyecto',
            field=models.BooleanField(default=False, help_text='Si esta activo, este tipo solo aplica para tareas de proyecto, no como actividad normal'),
        ),
    ]
