# Generated by Django 5.0.14 on 2026-06-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_remove_actividad_es_flash'),
        ('estructura', '0005_remove_area_empresa_alter_area_nombre_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('nombre', 'subarea', 'tipo_actividad')},
        ),
    ]
