# Generated by Django 5.0.14 on 2026-05-28 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_auditlogchange_auditsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=30)),
                ('valor_anterior', models.JSONField(blank=True, default=dict)),
                ('valor_nuevo', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncs_ejecutados', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Sincronizacion',
                'verbose_name_plural': 'Logs de Sincronizacion',
                'db_table': 'sync_log',
                'ordering': ['-fecha'],
            },
        ),
    ]
